"""
BD Buddy — Page 3: Official Grading Key, Trust Model & Document Info
"""

import os
from reportlab.lib import colors
from reportlab.lib.units import mm

from shared import (
    PAGE_W, PAGE_H, MARGIN_LEFT, MARGIN_RIGHT, CONTENT_W,
    BRAND_VIOLET, BDU_BLUE, DARK_SLATE, TABLE_SLATE,
    BORDER_GRAY, BORDER_LIGHT, MUTED, TEXT_BLACK,
    NAVY_BG, BADGE_GOLD, BG_LIGHT,
    DISCLAIMER_BG, DISCLAIMER_BORDER, DISCLAIMER_TITLE, DISCLAIMER_BODY,
    ty, make_qr,
    draw_security_layers, draw_standard_footer, draw_common_header,
)


GRADES = [
    ("A+",  "4.00", "85+"),
    ("A",   "4.00", "85+"),
    ("A-",  "3.75", "80-84"),
    ("B+",  "3.50", "75-79"),
    ("B",   "3.00", "70-74"),
    ("B-",  "2.75", "65-69"),
    ("C+",  "2.50", "60-64"),
    ("C",   "2.00", "50-59"),
    ("D",   "1.00", "40-49"),
    ("F",   "0.00", "<40"),
]


# ============================================================
# GRADING TABLE (single row)
# ============================================================
def _draw_grading_table(c, top_y):
    cell_w = CONTENT_W / 10.0
    table_x = MARGIN_LEFT
    table_h = 16

    # Outer border
    c.setStrokeColor(BORDER_GRAY)
    c.setLineWidth(0.4)
    c.rect(table_x, ty(top_y + table_h), CONTENT_W, table_h * mm, fill=0, stroke=1)

    # Horizontal dividers
    for offset in [6, 11]:
        c.line(table_x, ty(top_y + offset), table_x + CONTENT_W, ty(top_y + offset))

    # Vertical dividers
    for i in range(1, 10):
        x = table_x + i * cell_w
        c.line(x, ty(top_y), x, ty(top_y + table_h))

    # Content
    for i, (grade, points, rng) in enumerate(GRADES):
        cx = table_x + i * cell_w + cell_w / 2

        c.setFillColor(BRAND_VIOLET)
        c.setFont("Helvetica-Bold", 10)
        c.drawCentredString(cx, ty(top_y + 4.5), grade)

        c.setFillColor(TABLE_SLATE)
        c.setFont("Helvetica", 8)
        c.drawCentredString(cx, ty(top_y + 9.5), points)

        c.setFillColor(MUTED)
        c.setFont("Helvetica", 7)
        c.drawCentredString(cx, ty(top_y + 14.5), rng)


# ============================================================
# DISCLAIMER (Option C: left title + right content)
# ============================================================
def _draw_disclaimer(c, top_y, height):
    box_x = MARGIN_LEFT
    box_w = CONTENT_W

    # Background box
    c.setFillColor(DISCLAIMER_BG)
    c.setStrokeColor(DISCLAIMER_BORDER)
    c.setLineWidth(0.8)
    c.roundRect(box_x, ty(top_y + height), box_w, height * mm, 3 * mm, fill=1, stroke=1)

    # Left title area (55mm wide)
    title_x = box_x + 6 * mm
    title_w = 50 * mm

    # Vertical divider between title and content
    divider_x = box_x + 60 * mm
    c.setStrokeColor(DISCLAIMER_BORDER)
    c.setLineWidth(0.4)
    c.line(divider_x, ty(top_y + height - 4), divider_x, ty(top_y + 4))

    # Warning icon (triangle)
    icon_cx = title_x + title_w / 2
    icon_cy = top_y + 12

    c.setStrokeColor(DISCLAIMER_TITLE)
    c.setFillColor(DISCLAIMER_TITLE)
    c.setLineWidth(0.8)
    icon_s = 6 * mm
    p = c.beginPath()
    p.moveTo(icon_cx, ty(icon_cy - 4))
    p.lineTo(icon_cx - icon_s / 2, ty(icon_cy + 3))
    p.lineTo(icon_cx + icon_s / 2, ty(icon_cy + 3))
    p.close()
    c.drawPath(p, stroke=1, fill=0)

    # Exclamation inside triangle
    c.setLineWidth(0.8)
    c.line(icon_cx, ty(icon_cy - 2), icon_cx, ty(icon_cy + 1))
    c.circle(icon_cx, ty(icon_cy + 2.3), 0.4, fill=1, stroke=0)

    # Title text — stacked lines
    c.setFillColor(DISCLAIMER_TITLE)
    c.setFont("Helvetica-Bold", 11)

    title_lines = [
        "CRITICAL",
        "DISCLAIMER",
        "& TRUST",
        "STANDARD",
    ]
    ty_line = top_y + 20
    for line in title_lines:
        c.drawCentredString(icon_cx, ty(ty_line), line)
        ty_line += 6

    # Right content area (starts at X = 65mm)
    content_x = box_x + 65 * mm
    content_w = box_w - 65 * mm - 4 * mm  # right margin

    body_blocks = [
        (
            "",
            [
                "BD Buddy is an UNOFFICIAL, student-built utility platform built",
                "to visualize live student portal data. This document is NOT",
                "officially compiled by BDU Administration.",
            ],
        ),
        (
            "",
            [
                "NO personal student credentials or academic transcripts are",
                "stored on our servers.",
            ],
        ),
        (
            "",
            [
                "The QR verification only confirms the ORIGIN of this document",
                "was generated by BD Buddy. It does not verify BDU's official seal.",
            ],
        ),
        (
            "",
            [
                "For official administrative use, always trust:",
                "    - studentportal.bdu.edu.et",
                "    - BDU Registrar Office",
                "    - BDU IT Department",
            ],
        ),
    ]

    c.setFillColor(DISCLAIMER_BODY)
    c.setFont("Helvetica", 8)

    y_body = top_y + 8
    for _label, lines in body_blocks:
        for line in lines:
            c.drawString(content_x, ty(y_body), line)
            y_body += 3.4
        y_body += 1.5  # block spacing


# ============================================================
# DOCUMENT METADATA PANEL
# ============================================================
def _draw_metadata_panel(c, top_y, serial, print_date, print_mode, data):
    box_x = MARGIN_LEFT
    box_w = CONTENT_W
    box_h = 26

    c.setFillColor(BG_LIGHT)
    c.setStrokeColor(BORDER_GRAY)
    c.setLineWidth(0.4)
    c.rect(box_x, ty(top_y + box_h), box_w, box_h * mm, fill=1, stroke=1)

    # Title band
    c.setFillColor(TABLE_SLATE)
    c.rect(box_x, ty(top_y + 6), box_w, 6 * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(box_x + 3 * mm, ty(top_y + 4.5), "DOCUMENT METADATA")

    # Two-column layout of metadata
    from datetime import datetime

    now = datetime.now()

    report_type = {
        "Cumulative": "Cumulative Grade Sheet",
        "Semester I": "Semester I Grade Report",
        "Semester II": "Semester II Grade Report",
    }.get(print_mode, "Grade Report")

    left_items = [
        ("Report Type:", report_type),
        ("Generator:", "BD Buddy v3.0"),
        ("Document ID:", serial),
    ]

    right_items = [
        ("Generated:", f"{print_date} at {now.strftime('%H:%M')}"),
        ("Format:", "A4 Portrait / 3-Page Certificate"),
        ("Verification:", "QR + Crypt-Checksum"),
    ]

    c.setFillColor(TEXT_BLACK)
    y_item = top_y + 12

    for (lbl, val) in left_items:
        c.setFont("Helvetica-Bold", 8)
        c.drawString(box_x + 5 * mm, ty(y_item), lbl)
        c.setFont("Helvetica", 8)
        c.drawString(box_x + 30 * mm, ty(y_item), val[:45])
        y_item += 4.5

    y_item = top_y + 12
    for (lbl, val) in right_items:
        c.setFont("Helvetica-Bold", 8)
        c.drawString(box_x + 100 * mm, ty(y_item), lbl)
        c.setFont("Helvetica", 8)
        c.drawString(box_x + 125 * mm, ty(y_item), val[:40])
        y_item += 4.5


# ============================================================
# ABOUT + CONTACT (side by side)
# ============================================================
def _draw_about_contact(c, top_y, height):
    gap = 4 * mm
    col_w = (CONTENT_W - gap) / 2

    left_x = MARGIN_LEFT
    right_x = MARGIN_LEFT + col_w + gap

    # ---- Left: About BD Buddy ----
    c.setFillColor(BG_LIGHT)
    c.setStrokeColor(BORDER_GRAY)
    c.setLineWidth(0.4)
    c.rect(left_x, ty(top_y + height), col_w, height * mm, fill=1, stroke=1)

    c.setFillColor(TABLE_SLATE)
    c.rect(left_x, ty(top_y + 6), col_w, 6 * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(left_x + 3 * mm, ty(top_y + 4.5), "ABOUT BD BUDDY")

    c.setFillColor(TEXT_BLACK)
    c.setFont("Helvetica", 8)
    y_l = top_y + 12
    about_lines = [
        "Free, student-built viewer for the BDU",
        "student portal. Presents real academic",
        "data in a clean, mobile-first interface.",
        "",
        "Live: bdu-portal.onrender.com",
        "Source: github.com/uniyo-dev/",
        "        BDU-student-vercel",
    ]
    for line in about_lines:
        c.drawString(left_x + 4 * mm, ty(y_l), line)
        y_l += 3.5

    # ---- Right: Contact ----
    c.setFillColor(BG_LIGHT)
    c.setStrokeColor(BORDER_GRAY)
    c.setLineWidth(0.4)
    c.rect(right_x, ty(top_y + height), col_w, height * mm, fill=1, stroke=1)

    c.setFillColor(TABLE_SLATE)
    c.rect(right_x, ty(top_y + 6), col_w, 6 * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(right_x + 3 * mm, ty(top_y + 4.5), "SUPPORT & CONTACT")

    c.setFillColor(TEXT_BLACK)
    c.setFont("Helvetica", 8)
    y_r = top_y + 12
    contact_rows = [
        ("Developer:", "Chalachew Agegn"),
        ("Telegram:", "@challengepr"),
        ("Email:", "chalachewagegn7@gmail.com"),
        ("Phone:", "0923093416"),
    ]
    for (lbl, val) in contact_rows:
        c.setFont("Helvetica-Bold", 8)
        c.drawString(right_x + 4 * mm, ty(y_r), lbl)
        c.setFont("Helvetica", 8)
        c.drawString(right_x + 22 * mm, ty(y_r), val)
        y_r += 4.5


# ============================================================
# QR GATEWAY
# ============================================================
def _draw_qr_gateway(c, top_y, verify_url):
    qr_h = 24

    c.setStrokeColor(BORDER_GRAY)
    c.setLineWidth(0.4)
    c.setDash(2, 2)
    c.rect(MARGIN_LEFT, ty(top_y + qr_h), CONTENT_W, qr_h * mm, fill=0, stroke=1)
    c.setDash()

    qr_img = make_qr(verify_url)
    c.drawImage(qr_img, MARGIN_LEFT + 3 * mm, ty(top_y + qr_h - 2),
                width=18 * mm, height=18 * mm, mask='auto')

    c.setFillColor(TEXT_BLACK)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(MARGIN_LEFT + 25 * mm, ty(top_y + 7),
                 "OFFICIAL VERIFICATION GATEWAY")

    c.setFillColor(TABLE_SLATE)
    c.setFont("Helvetica", 8)
    c.drawString(MARGIN_LEFT + 25 * mm, ty(top_y + 13),
                 "Verify structural signature online. Unaltered authentic files pass")
    c.drawString(MARGIN_LEFT + 25 * mm, ty(top_y + 17),
                 "crypt-checksum validations.")

    c.setFillColor(MUTED)
    c.setFont("Helvetica", 7.5)
    c.drawString(MARGIN_LEFT + 25 * mm, ty(top_y + 21),
                 f"Verification Token: {verify_url[:70]}")


# ============================================================
# MAIN PAGE 3 ENTRY
# ============================================================
def draw_page_three(c, data, serial, print_date, verify_url):
    """Render page 3 onto canvas c."""

    draw_security_layers(c, watermark_text="RULES KEY")
    draw_common_header(c, serial, print_date)

    # Page titles
    c.setFillColor(TEXT_BLACK)
    c.setFont("Helvetica-Bold", 13)
    c.drawCentredString(PAGE_W / 2, ty(36), "BAHIR DAR UNIVERSITY")

    c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(PAGE_W / 2, ty(42), "OFFICIAL GRADING KEY SYSTEM")

    # Grading table header band
    band_top = 50
    band_h = 5
    c.setFillColor(DARK_SLATE)
    c.rect(MARGIN_LEFT, ty(band_top + band_h), CONTENT_W, band_h * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(MARGIN_LEFT + 3 * mm, ty(band_top + 3.5),
                 "BAHIR DAR UNIVERSITY GRADING BENCHMARKS")

    # Grading table
    _draw_grading_table(c, top_y=57)

    # Disclaimer (Option C)
    _draw_disclaimer(c, top_y=80, height=55)

    # Metadata panel
    print_mode = data.get("printMode", "Cumulative")
    _draw_metadata_panel(c, top_y=140, serial=serial,
                         print_date=print_date, print_mode=print_mode, data=data)

    # About + Contact side-by-side
    _draw_about_contact(c, top_y=172, height=28)

    # QR gateway
    _draw_qr_gateway(c, top_y=205, verify_url=verify_url)

    # Footer
    draw_standard_footer(c)
    c.showPage()
    c.save()
